#收件人信息配置
ToEmail:
  topKeFu:
#    2278417331@qq.com
    479747481@qq.com,1261309200@qq.com,709363066@qq.com
  gwfREmail:
#    2278417331@qq.com
    2278417331@qq.com
#-----------------------------------------------------------------------------
#启动端口配置
server:
#  port: 9091 #客服端口
  port: 9092 #自用端口
  context-path: /GwfAutoWorkTF
#-----------------------------------------------------------------------------
#log4j2配置文件
logging:
  config: classpath:config/log4j2.xml

#-----------------------------------------------------------------------------
#email配置
spring:
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com
    host: smtp.163.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: 18238621523@163.com
    #授权码
    password: KJKQKLXMJJJZDJAX
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  mvc:
    view:
      prefix: /page/
      suffix: .html
    favicon:
      enabled: false
  thymeleaf:
    prefix: /static